---@meta
-- AUTO-GENERATED by sleet-cli. DO NOT EDIT MANUALLY.
-- Regenerate with: sleet generate <your-schema.lua>
-- https://github.com/SleetCo/sleet-orm

-- ────────────────────────────────────────────────
-- Row shapes — returned by execute() with full type inference.
-- No manual ---@type needed: db.select().from(s.users).execute()
-- automatically resolves to UsersRecord[] via SleetTableDef<R>.
-- ────────────────────────────────────────────────

---@class PlayersRecord
---@field id                       integer 玩家自增ID
---@field identifier               string 玩家唯一标识符（Steam/Discord）
---@field bank                     integer 银行余额
---@field job                      string 当前职业
---@field metadata                 table 扩展数据（许可证、角色信息等）
---@field name                     string 玩家名称
---@field money                    integer 现金
---@field is_admin                 boolean 是否为管理员
---@field last_seen                string 最后在线时间
---@field created_at               string 账号创建时间

---@class GangsRecord
---@field owner                    string 帮主标识符
---@field bank                     integer 帮派金库余额
---@field max_grade                integer 最高等级数
---@field created_at               string 创建时间
---@field id                       integer 帮派自增ID
---@field name                     string 帮派唯一名称
---@field label                    string 帮派显示名称

---@class GangMembersRecord
---@field grade_name               string 等级名称
---@field joined_at                string 加入时间
---@field id                       integer 记录ID
---@field gang_id                  integer 所属帮派ID
---@field identifier               string 成员标识符
---@field grade                    integer 成员等级（0 = 新兵）

---@class ItemsRecord
---@field name                     string 物品唯一名称（作为主键）
---@field label                    string 物品显示名称
---@field weight                   number 物品重量（克）
---@field stack                    boolean 是否可叠加
---@field usable                   boolean 是否可使用
---@field description              string 物品描述

---@class InventoryRecord
---@field id                       integer 记录ID
---@field identifier               string 玩家标识符
---@field item                     string 物品名称
---@field amount                   integer 数量
---@field metadata                 table 物品元数据（耐久、序列号等）

-- ────────────────────────────────────────────────
-- Table objects — each extends SleetTableDef<XxxRecord> so that
-- the generic fun<R> in SleetPreSelectBuilder.from() can infer R.
-- ────────────────────────────────────────────────

---@class PlayersTable: SleetTableDef<PlayersRecord>
---@field id                       ColumnDef<integer> 玩家自增ID
---@field identifier               ColumnDef<string> 玩家唯一标识符（Steam/Discord）
---@field bank                     ColumnDef<integer> 银行余额
---@field job                      ColumnDef<string> 当前职业
---@field metadata                 ColumnDef<table> 扩展数据（许可证、角色信息等）
---@field name                     ColumnDef<string> 玩家名称
---@field money                    ColumnDef<integer> 现金
---@field is_admin                 ColumnDef<boolean> 是否为管理员
---@field last_seen                ColumnDef<string> 最后在线时间
---@field created_at               ColumnDef<string> 账号创建时间

---@class GangsTable: SleetTableDef<GangsRecord>
---@field owner                    ColumnDef<string> 帮主标识符
---@field bank                     ColumnDef<integer> 帮派金库余额
---@field max_grade                ColumnDef<integer> 最高等级数
---@field created_at               ColumnDef<string> 创建时间
---@field id                       ColumnDef<integer> 帮派自增ID
---@field name                     ColumnDef<string> 帮派唯一名称
---@field label                    ColumnDef<string> 帮派显示名称

---@class GangMembersTable: SleetTableDef<GangMembersRecord>
---@field grade_name               ColumnDef<string> 等级名称
---@field joined_at                ColumnDef<string> 加入时间
---@field id                       ColumnDef<integer> 记录ID
---@field gang_id                  ColumnDef<integer> 所属帮派ID
---@field identifier               ColumnDef<string> 成员标识符
---@field grade                    ColumnDef<integer> 成员等级（0 = 新兵）

---@class ItemsTable: SleetTableDef<ItemsRecord>
---@field name                     ColumnDef<string> 物品唯一名称（作为主键）
---@field label                    ColumnDef<string> 物品显示名称
---@field weight                   ColumnDef<number> 物品重量（克）
---@field stack                    ColumnDef<boolean> 是否可叠加
---@field usable                   ColumnDef<boolean> 是否可使用
---@field description              ColumnDef<string> 物品描述

---@class InventoryTable: SleetTableDef<InventoryRecord>
---@field id                       ColumnDef<integer> 记录ID
---@field identifier               ColumnDef<string> 玩家标识符
---@field item                     ColumnDef<string> 物品名称
---@field amount                   ColumnDef<integer> 数量
---@field metadata                 ColumnDef<table> 物品元数据（耐久、序列号等）

-- ────────────────────────────────────────────────
-- Per-table select builders — concrete, no generics.
-- execute() returns the precise XxxRecord[] type.
-- ────────────────────────────────────────────────

---@class PlayersSelectBuilder
---@field where     fun(cond: table): PlayersSelectBuilder
---@field limit     fun(n: integer): PlayersSelectBuilder
---@field offset    fun(n: integer): PlayersSelectBuilder
---@field orderBy   fun(col: ColumnDef, dir?: string): PlayersSelectBuilder
---@field groupBy   fun(col: ColumnDef): PlayersSelectBuilder
---@field leftJoin  fun(tbl: table, on: table): PlayersSelectBuilder
---@field innerJoin fun(tbl: table, on: table): PlayersSelectBuilder
---@field rightJoin fun(tbl: table, on: table): PlayersSelectBuilder
---@field execute   fun(): PlayersRecord[]
---@field toSQL     fun(): string, table

---@class GangsSelectBuilder
---@field where     fun(cond: table): GangsSelectBuilder
---@field limit     fun(n: integer): GangsSelectBuilder
---@field offset    fun(n: integer): GangsSelectBuilder
---@field orderBy   fun(col: ColumnDef, dir?: string): GangsSelectBuilder
---@field groupBy   fun(col: ColumnDef): GangsSelectBuilder
---@field leftJoin  fun(tbl: table, on: table): GangsSelectBuilder
---@field innerJoin fun(tbl: table, on: table): GangsSelectBuilder
---@field rightJoin fun(tbl: table, on: table): GangsSelectBuilder
---@field execute   fun(): GangsRecord[]
---@field toSQL     fun(): string, table

---@class GangMembersSelectBuilder
---@field where     fun(cond: table): GangMembersSelectBuilder
---@field limit     fun(n: integer): GangMembersSelectBuilder
---@field offset    fun(n: integer): GangMembersSelectBuilder
---@field orderBy   fun(col: ColumnDef, dir?: string): GangMembersSelectBuilder
---@field groupBy   fun(col: ColumnDef): GangMembersSelectBuilder
---@field leftJoin  fun(tbl: table, on: table): GangMembersSelectBuilder
---@field innerJoin fun(tbl: table, on: table): GangMembersSelectBuilder
---@field rightJoin fun(tbl: table, on: table): GangMembersSelectBuilder
---@field execute   fun(): GangMembersRecord[]
---@field toSQL     fun(): string, table

---@class ItemsSelectBuilder
---@field where     fun(cond: table): ItemsSelectBuilder
---@field limit     fun(n: integer): ItemsSelectBuilder
---@field offset    fun(n: integer): ItemsSelectBuilder
---@field orderBy   fun(col: ColumnDef, dir?: string): ItemsSelectBuilder
---@field groupBy   fun(col: ColumnDef): ItemsSelectBuilder
---@field leftJoin  fun(tbl: table, on: table): ItemsSelectBuilder
---@field innerJoin fun(tbl: table, on: table): ItemsSelectBuilder
---@field rightJoin fun(tbl: table, on: table): ItemsSelectBuilder
---@field execute   fun(): ItemsRecord[]
---@field toSQL     fun(): string, table

---@class InventorySelectBuilder
---@field where     fun(cond: table): InventorySelectBuilder
---@field limit     fun(n: integer): InventorySelectBuilder
---@field offset    fun(n: integer): InventorySelectBuilder
---@field orderBy   fun(col: ColumnDef, dir?: string): InventorySelectBuilder
---@field groupBy   fun(col: ColumnDef): InventorySelectBuilder
---@field leftJoin  fun(tbl: table, on: table): InventorySelectBuilder
---@field innerJoin fun(tbl: table, on: table): InventorySelectBuilder
---@field rightJoin fun(tbl: table, on: table): InventorySelectBuilder
---@field execute   fun(): InventoryRecord[]
---@field toSQL     fun(): string, table

-- ────────────────────────────────────────────────
-- SleetPreSelectBuilder.from overloads
-- db.select().from(s.users) → UsersSelectBuilder
-- ────────────────────────────────────────────────

---@class SleetPreSelectBuilder
---@field from fun(tbl: PlayersTable): PlayersSelectBuilder
---@field from fun(tbl: GangsTable): GangsSelectBuilder
---@field from fun(tbl: GangMembersTable): GangMembersSelectBuilder
---@field from fun(tbl: ItemsTable): ItemsSelectBuilder
---@field from fun(tbl: InventoryTable): InventorySelectBuilder

-- ────────────────────────────────────────────────
-- Sleet.table overloads — sl.table('users', ...) → UsersTable
-- These take priority over the generic fallback in annotations.lua.
-- ────────────────────────────────────────────────

---@overload fun(name: 'players', columns: table): PlayersTable
---@overload fun(name: 'gangs', columns: table): GangsTable
---@overload fun(name: 'gang_members', columns: table): GangMembersTable
---@overload fun(name: 'items', columns: table): ItemsTable
---@overload fun(name: 'inventory', columns: table): InventoryTable
---@diagnostic disable-next-line: inject-field
function Sleet.table(name, columns) end
