-- AUTO-GENERATED by sleet-cli. DO NOT EDIT MANUALLY.
-- Regenerate with: sleet sql <your-schema.lua>
-- https://github.com/SleetCo/sleet-orm

CREATE TABLE IF NOT EXISTS `players` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '玩家自增ID',
    `identifier` VARCHAR(64) NOT NULL UNIQUE COMMENT '玩家唯一标识符（Steam/Discord）',
    `name` VARCHAR(255) NOT NULL COMMENT '玩家名称',
    `money` INT DEFAULT 500 COMMENT '现金',
    `bank` INT DEFAULT 2500 COMMENT '银行余额',
    `is_admin` TINYINT(1) DEFAULT 0 COMMENT '是否为管理员',
    `job` VARCHAR(64) DEFAULT 'unemployed' COMMENT '当前职业',
    `metadata` JSON NULL COMMENT '扩展数据（许可证、角色信息等）',
    `last_seen` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '最后在线时间（自动更新）',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '账号创建时间',
    `deleted_at` TIMESTAMP NULL COMMENT '软删除时间戳',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gangs` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '帮派自增ID',
    `name` VARCHAR(64) NOT NULL UNIQUE COMMENT '帮派唯一名称',
    `label` VARCHAR(128) NOT NULL COMMENT '帮派显示名称',
    `owner` VARCHAR(64) NULL COMMENT '帮主标识符',
    `bank` BIGINT DEFAULT 0 COMMENT '帮派金库余额',
    `max_grade` TINYINT DEFAULT 4 COMMENT '最高等级数',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`owner`) REFERENCES `players` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `gang_members` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    `gang_id` INT NOT NULL COMMENT '所属帮派ID',
    `identifier` VARCHAR(64) NOT NULL COMMENT '成员标识符',
    `grade` TINYINT DEFAULT 0 COMMENT '成员等级（0 = 新兵）',
    `grade_name` VARCHAR(64) DEFAULT 'Recruit' COMMENT '等级名称',
    `joined_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`gang_id`) REFERENCES `gangs` (`id`),
    FOREIGN KEY (`identifier`) REFERENCES `players` (`identifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `items` (
    `name` VARCHAR(64) NOT NULL COMMENT '物品唯一名称（作为主键）',
    `label` VARCHAR(128) NOT NULL COMMENT '物品显示名称',
    `weight` DECIMAL(8,2) DEFAULT 0 COMMENT '物品重量（克）',
    `stack` TINYINT(1) DEFAULT 1 COMMENT '是否可叠加',
    `usable` TINYINT(1) DEFAULT 0 COMMENT '是否可使用',
    `description` TEXT NULL COMMENT '物品描述',
    PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `inventory` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
    `identifier` VARCHAR(64) NOT NULL COMMENT '玩家标识符',
    `item` VARCHAR(64) NOT NULL COMMENT '物品名称',
    `amount` INT DEFAULT 1 COMMENT '数量',
    `metadata` JSON NULL COMMENT '物品元数据（耐久、序列号等）',
    PRIMARY KEY (`id`),
    FOREIGN KEY (`identifier`) REFERENCES `players` (`identifier`),
    FOREIGN KEY (`item`) REFERENCES `items` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

